import { describe, expect, it } from "vitest";

import { renderAmbientToolsBlock, renderToolsAmbientDts, type MethodLike } from "../src/index.js";

function method(overrides: Partial<MethodLike> & Pick<MethodLike, "namespaceName" | "path">): MethodLike {
  return {
    inputType: "FooInput",
    outputType: "FooOutput",
    resultType: "FooResult",
    inputSchema: { type: "object" },
    examples: [],
    ...overrides
  };
}

describe("renderToolsAmbientDts", () => {
  it("renders the ambient tools surface referencing sibling types", () => {
    const dts = renderToolsAmbientDts(
      [
        method({
          namespaceName: "grafana",
          path: ["datasources", "list"],
          inputType: "GrafanaDatasourcesListInput",
          outputType: "GrafanaDatasourcesListOutput"
        }),
        method({
          namespaceName: "grafana",
          path: ["alerting", "rules", "get"],
          inputType: "GrafanaAlertingRulesGetInput",
          outputType: "GrafanaAlertingRulesGetOutput",
          inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }
        })
      ],
      { header: "/* Generated by Tack. Do not edit directly. */" }
    );

    expect(dts.startsWith("/* Generated by Tack. Do not edit directly. */")).toBe(true);
    expect(dts).toContain('import type {\n  GrafanaAlertingRulesGetInput,');
    expect(dts).toContain('} from "./types.js";');
    expect(dts).toContain("type CodeModeResult<T> =");
    expect(dts).toContain("declare global {");
    expect(dts).toContain('readonly "grafana": {');
    expect(dts).toContain('readonly "alerting": {');
    expect(dts).toContain(
      '"list"(args?: GrafanaDatasourcesListInput): Promise<CodeModeResult<GrafanaDatasourcesListOutput>>;'
    );
    expect(dts).toContain(
      '"get"(args: GrafanaAlertingRulesGetInput): Promise<CodeModeResult<GrafanaAlertingRulesGetOutput>>;'
    );
    expect(dts).toContain("call<T = unknown>(path: string");
    expect(dts).toContain("function emit(value: unknown): void;");
    expect(dts).toContain("export {};");
  });

  it("is deterministic regardless of input order", () => {
    const a = method({ namespaceName: "x", path: ["a"], inputType: "AI", outputType: "AO" });
    const b = method({ namespaceName: "x", path: ["b"], inputType: "BI", outputType: "BO" });
    expect(renderToolsAmbientDts([a, b])).toBe(renderToolsAmbientDts([b, a]));
  });

  it("drops the colliding builtin signature when a namespace shadows one", () => {
    const dts = renderToolsAmbientDts([
      method({ namespaceName: "search", path: ["run"], inputType: "SI", outputType: "SO" })
    ]);
    expect(dts).toContain('readonly "search": {');
    expect(dts).toContain("// note:");
    expect(dts).not.toContain("search(input?: {");
  });

  it("renderAmbientToolsBlock is the tools block alone — no header, import, or aliases", () => {
    const block = renderAmbientToolsBlock([
      method({ namespaceName: "grafana", path: ["datasources", "list"], inputType: "GDLI", outputType: "GDLO" })
    ]);
    expect(block).toContain("declare global {");
    expect(block).toContain("const tools: {");
    expect(block).toContain('readonly "grafana": {');
    expect(block).toContain('"list"(args?: GDLI): Promise<CodeModeResult<GDLO>>;');
    expect(block).toContain("call<T = unknown>(path: string");
    expect(block).toContain("function emit(value: unknown): void;");
    expect(block.trimEnd().endsWith("export {};")).toBe(true);
    expect(block).not.toContain('from "./types.js"');
    expect(block).not.toContain("type CodeModeResult<T>");
    // renderToolsAmbientDts wraps the same block with the header/import/aliases
    expect(renderToolsAmbientDts([
      method({ namespaceName: "grafana", path: ["datasources", "list"], inputType: "GDLI", outputType: "GDLO" })
    ])).toContain(block.trimEnd());
  });
});
