import type { JsonSchema } from "@tack/core";

export interface GeneratedMethod {
  readonly namespaceName: string;
  readonly serverId: string;
  readonly path: readonly string[];
  readonly pathString: string;
  readonly fullPathString: string;
  readonly toolId: string;
  readonly upstreamName: string;
  readonly description?: string;
  readonly examples: readonly string[];
  readonly inputSchema: JsonSchema;
  readonly outputSchema?: JsonSchema;
  readonly injectedArgs?: Readonly<Record<string, string>>;
  readonly inputType: string;
  readonly outputType: string;
  readonly resultType: string;
}

export interface GeneratedFile {
  readonly fileName: string;
  readonly contents: string;
}

export const SDK_RUNTIME_MANIFEST_GENERATED_AT = "1970-01-01T00:00:00.000Z";
export const GENERATED_FILE_HEADER = "/* Generated by Tack. Do not edit directly. */";
